### PR TITLE
settings: Add an option to enable hot corners in fullscreen

### LINKED ISSUE #13127: Hotcorners not working on fullscreen apps
### Distribution

22.2

### Package version

6.4.8

### Graphics hardware in use

Intel Raptor Lake-P [Iris Xe Graphics], NVIDIA GA107M [GeForce RTX 3050 4GB Laptop GPU]

### Frequency

Always

### Bug description

Hotcorners not working at all with fullscreen apps
This includes Steam bigscreen, Youtube

### Steps to reproduce

1- settings > hot corner > enable any hotcorner
2- test hot corner (working)
3- open a web browser
4- go to youtube.com
5- open any video
6- play it fullscreen
7- try to activate this hotcorner (not working)

### Expected behavior

there should be an option or maybe this option should be working by default that makes hotcorners work with fullscreen apps

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by baronleonardo**
fixes #13127

### CODE REVIEW

File: js/ui/hotCorner.js [hunk 1]
```diff
@@ -325,6 +331,8 @@ var HotCornerManager = class {
 
     update() {
         let options = global.settings.get_strv(OVERVIEW_CORNERS_KEY);
+        let is_fullscreen = global.settings.get_boolean(CORNERS_FULLSCREEN_KEY);
+
```
Comment (mtwebster) [inline js/ui/hotCorner.js:336]: Please add a change listener for this setting (a few lines above in the constructor), otherwise a Cinnamon restart is required for a change to take effect.

Comment (baronleonardo) [reply js/ui/hotCorner.js:336]: done
