### PR TITLE
Fix OSD level animation lag when using gesture volume control

### LINKED ISSUE #12760: Volume OSD is very laggy
### Distribution

Mint 22.1

### Package version

6.4.8

### Graphics hardware in use

Intel Corporation Raptor Lake-P [Iris Xe Graphics]

### Frequency

Always

### Bug description

After issue #12646 it seems like the volume OSD has gotten very laggy while using the touchpad gesture for changing volume, in the bottom right volume applet it moves smoothly but in the OSD it seems to move very laggy (could be because of the animation), the icon does seem to change correctly though.

### Steps to reproduce

Use the touchpad gesture for volumes with OSD enabled.

Video attached:
https://github.com/user-attachments/assets/849a0429-3164-40c6-8f99-3122621fb89d

### Expected behavior

To not lag and move smoothly just like the volume applet.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by screem02**
Fixes visual laggy appearance of level animation in OSD when using touchpad gesture volume control, from #12760.

### Need
The previous behavior forces 100ms LEVEL_ANIMATION_TIME transition for all level changes, even minuscule ones, causes extreme lag when using gestures. (addressable by throttling alone for now)

### Fix
- Throttled osdWindowManager.show() call in similar fashion as in zoom control class, prevent event flooding.

- Initially made other changes, but realised they were not really necessary and felt bloaty, throttling works fine.

Thanks for reviewing.

Closes #12760

### CODE REVIEW

**Comment by screem02** [comment]
hey @mtwebster , sorry for the bother, but [c8cb4ec](https://github.com/linuxmint/cinnamon/pull/13338/commits/c8cb4ecc064ffb1bfdaa55c9e236c5ac4653698e) is failing on mint22 build but the later commit is passing, also since I'm new can you check if the code is following good standards.
Thank you!

**Comment by mtwebster** [comment]
Hi sorry I missed your comment, don't worry about those builds - they're meaningless for commits like this that don't touch compiled code, and there are many reasons unrelated to a pull request that can cause failures as well.

**Comment by screem02** [comment]
I made a typo in my code and crashed my ui, thought something was wrong with the code so closed the pull request and checked the code, no issue here.
We can add some more good looking ui stuff but I removed the extra funcs, vars and conts I added, they felt bloaty.

File: js/ui/gestures/actions.js
Comment (mtwebster) [inline js/ui/gestures/actions.js:407]: Missing `this.last_time = 0`? (refer to ZoomAction for comparison)

File: js/ui/gestures/actions.js [hunk 1]
```diff
@@ -320,9 +320,12 @@ var VolumeAction = class extends BaseAction {
             this.max_volume = mixer.get_vol_max_norm();
 
         this.pct_step = Math.ceil(this.max_volume / 100);
+
+        this.last_time = 0;
+        this.poll_interval = 50 * 1000;
```
Comment (mtwebster) [inline js/ui/gestures/actions.js]: Since the poll interval is used in two places, maybe it should just be a constant for the entire file and we get rid of poll_interval altogether. 

like `const CONTINUOUS_ACTION_POLL_INTERVAL = 50 * 1000;`

File: js/ui/gestures/actions.js
Comment (mtwebster) [inline js/ui/gestures/actions.js:438]: Should there be a final `Main.osdWindowManager.show()` in `end()`? It may have been skipped during the update, and the volume ends up not being the same as what the user last saw in an Osd.

Comment (screem02) [reply js/ui/gestures/actions.js:407]: added this.last_time = 0;

Comment (screem02) [reply js/ui/gestures/actions.js:438]: added the show() fnc to end, I lazily thought the visual and actual volume diff in these cases would be very small, but yeah we should try to present it cleanly.

Comment (screem02) [reply js/ui/gestures/actions.js:438]: is the change correct or should I have gone with this:
`const percentage = Math.ceil(sink.volume / this.pct_step).clamp(0, 100);
Main.osdWindowManager.show(-1, this._get_volume_icon(percentage), null, percent, false);`

Comment (mtwebster) [reply js/ui/gestures/actions.js:438]: this is ok i think.
